### ISSUE TITLE
Exception: [TypeError: ip.indexOf is not a function]

### ISSUE THREAD

**Issue by jerome83136** [bpaquet/node-logstash#129]
Hello,

After starting node-logstash, I have seen this in my logs:

Exception has been catch, it' a bug
Please submit an issue on https://github.com/bpaquet/node-logstash
Exception: [TypeError: ip.indexOf is not a function]
TypeError: ip.indexOf is not a function
    at FilterGeoip.process (/products/node-logstash/lib/filters/filter_geoip.js:92:8)
    at FilterGeoip.<anonymous> (/products/node-logstash/lib/lib/base_filter.js:21:24)
    at emitOne (events.js:77:13)
    at FilterGeoip.emit (events.js:169:7)
    at FilterRegex.<anonymous> (/products/node-logstash/lib/agent.js:248:14)
    at emitOne (events.js:77:13)
    at FilterRegex.emit (events.js:169:7)
    at FilterRegex.<anonymous> (/products/node-logstash/lib/lib/base_filter.js:27:18)
    at emitOne (events.js:77:13)
    at FilterRegex.emit (events.js:169:7)

So I have submitted this issue.
Hope it will help.

Best regards
Jérôme

**Comment by bpaquet** [comment]
What contains your ip field ? An array ? A hash ? The geoip filter expect a
string.
--
Bertrand

**Comment by jerome83136** [comment]
On Elasticsearch the "clientip" field if mapped as an "IP" field:

```
"clientip": {
            "index": "analyzed",
            "type": "ip"
          },
```

The logstash config is:
```
 geoip {
  field => clientip
  cache_size => 1000
 }
```
Please notice there are GeoIP fields (clientip) which are working fine.
The problem does not seem to occur for each line of log.

Jérôme

**Comment by bpaquet** [comment]
The ``clientip`` should not contains a string.
I can ensure the field is a string. That will remove the exception. But the interesting point is what is it if it's not a string ? Any idea ?
