### ISSUE TITLE
[TypeError: ip.indexOf is not a function]

### ISSUE THREAD

**Issue by jerome83136** [bpaquet/node-logstash#135]
Hello,

My node-logstash processes have started to crash randomly some weekd ago.

I just have to restart the process with the same config and it works some times, then it crash again later..

That's strange since I didn't change anything in my config.

I have seen these lines in my logs. I think node-logstash is crashing because of this, but what is wrong with this ?

Thanks for your help

Best regards
Jérôme

```
[Wed, 24 Aug 2016 22:59:06 GMT] ERROR Exception has been catch, it' a bug
[Wed, 24 Aug 2016 22:59:06 GMT] ERROR Please submit an issue on https://github.com/bpaquet/node-logstash
[Wed, 24 Aug 2016 22:59:06 GMT] ERROR Exception: [TypeError: ip.indexOf is not a function]
[Wed, 24 Aug 2016 22:59:06 GMT] ERROR TypeError: ip.indexOf is not a function
    at FilterGeoip.process (/products/node-logstash/lib/filters/filter_geoip.js:92:8)
    at FilterGeoip.<anonymous> (/products/node-logstash/lib/lib/base_filter.js:21:24)
    at emitOne (events.js:77:13)
    at FilterGeoip.emit (events.js:169:7)
    at FilterRegex.<anonymous> (/products/node-logstash/lib/agent.js:248:14)
    at emitOne (events.js:77:13)
    at FilterRegex.emit (events.js:169:7)
    at FilterRegex.<anonymous> (/products/node-logstash/lib/lib/base_filter.js:27:18)
    at emitOne (events.js:77:13)
    at FilterRegex.emit (events.js:169:7)
[Thu, 25 Aug 2016 01:09:11 GMT] ERROR tail: /path/to/logfile1.log: file truncated
[Thu, 25 Aug 2016 01:09:19 GMT] ERROR tail: /path/to/logfile2.log: file truncated
[Thu, 25 Aug 2016 01:09:25 GMT] ERROR tail: /path/to/logfile3.log: file truncated
[Thu, 25 Aug 2016 01:09:30 GMT] ERROR tail: /path/to/logfile4.log: file truncated
[Thu, 25 Aug 2016 01:19:10 GMT] ERROR tail: /path/to/logfile1.log: file truncated
[Thu, 25 Aug 2016 01:19:21 GMT] ERROR tail: /path/to/logfile2.log: file truncated
[Thu, 25 Aug 2016 01:19:21 GMT] ERROR tail: /path/to/logfile3.log: file truncated
[Thu, 25 Aug 2016 01:19:28 GMT] ERROR tail: /path/to/logfile4.log: file truncated
[Thu, 25 Aug 2016 01:31:06 GMT] ERROR tail: /path/to/logfile3.log: file truncated
[Thu, 25 Aug 2016 01:31:17 GMT] ERROR tail: /path/to/logfile1.log: file truncated
[Thu, 25 Aug 2016 01:31:17 GMT] ERROR tail: /path/to/logfile4.log: file truncated
[Thu, 25 Aug 2016 01:31:17 GMT] ERROR tail: /path/to/logfile2.log: file truncated
[Thu, 25 Aug 2016 01:46:23 GMT] ERROR Exception has been catch, it' a bug
[Thu, 25 Aug 2016 01:46:23 GMT] ERROR Please submit an issue on https://github.com/bpaquet/node-logstash
[Thu, 25 Aug 2016 01:46:23 GMT] ERROR Exception: [TypeError: ip.indexOf is not a function]
[Thu, 25 Aug 2016 01:46:23 GMT] ERROR TypeError: ip.indexOf is not a function
    at FilterGeoip.process (/products/node-logstash/lib/filters/filter_geoip.js:92:8)
    at FilterGeoip.<anonymous> (/products/node-logstash/lib/lib/base_filter.js:21:24)
    at emitOne (events.js:77:13)
    at FilterGeoip.emit (events.js:169:7)
    at FilterRegex.<anonymous> (/products/node-logstash/lib/agent.js:248:14)
    at emitOne (events.js:77:13)
    at FilterRegex.emit (events.js:169:7)
    at FilterRegex.<anonymous> (/products/node-logstash/lib/lib/base_filter.js:27:18)
    at emitOne (events.js:77:13)
    at FilterRegex.emit (events.js:169:7)
```

**Comment by bpaquet** [comment]
Did you change your node version ?

**Comment by jerome83136** [comment]
Hello,
No, I did not change anything on the install.

Best regards
Jerome

Le 22 sept. 2016 8:49 AM, "Bertrand Paquet" <notifications@github.com> a
écrit :

Did you change your node version ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bpaquet/node-logstash/issues/135#issuecomment-248826009>,
or mute the thread
