### ISSUE TITLE
Beats Input

### ISSUE THREAD

**Issue by zeeshanalisyed** [bpaquet/node-logstash#147]
I want to get data from filebeat into node-logstash now My input configurations look like this,
```
input {
  beats {
    host => 0.0.0.0
    port => 12345
  }
}
```
But whenever I setup beats as input plugin i see below exeption
```
ERROR Error: Cannot find module 'inputs/input_beats'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at LogstashAgent.configure (/home/node-logstash/lib/agent.js:130:16)
    at LogstashAgent.<anonymous> (/home/node-logstash/lib/agent.js:204:10)
    at iterate (/home/node-logstash/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/home/node-logstash/node_modules/async/lib/async.js:165:9)
    at LogstashAgent.start_modules (/home/node-logstash/lib/agent.js:203:9)
    at LogstashAgent.start_inputs (/home/node-logstash/lib/agent.js:225:8)

```
from the above given exception, i guess you don't have beats module and you are using another way or configuration to get data from filebeat.

Now I have two questions.

**1. Can I get data from filebeat?
2. If yes Please tell me the configuration?**

**Comment by zeeshanalisyed** [comment]
Never Mind I got it

**Comment by sundara20** [comment]
Hey, could you please share whatever you found out?
