### ISSUE TITLE
Mistake in `mutate` part?

### ISSUE THREAD

**Issue by whilgeek** [bpaquet/node-logstash#93]
When I using the code in `mutate` part

```
filter://mutate_replace?toto&from=\\.&to=-
```
node-logstash reported:

```
ERROR Unable to load urls from command line
ERROR Error: Unable to extract plugin name from mutate_replace?toto&from=\\.&to=-
    at LogstashAgent.configure (/home/ubuntu/node-logstash/lib/agent.js:119:21)
    at LogstashAgent.start_modules (/home/ubuntu/node-logstash/lib/agent.js:199:8)
    at LogstashAgent.<anonymous> (/home/ubuntu/node-logstash/lib/agent.js:209:12)
    at LogstashAgent.<anonymous> (/home/ubuntu/node-logstash/lib/agent.js:253:5)
    at LogstashAgent.<anonymous> (/home/ubuntu/node-logstash/lib/agent.js:205:5)
    at LogstashAgent.<anonymous> (/home/ubuntu/node-logstash/lib/agent.js:138:9)
    at FilterGrok.<anonymous> (/home/ubuntu/node-logstash/lib/lib/base_filter.js:36:5)
    at FilterGrok.<anonymous> (/home/ubuntu/node-logstash/lib/lib/base_component.js:190:7)
    at FilterGrok.BaseComponent.runHooks (/home/ubuntu/node-logstash/lib/lib/base_component.js:70:12)
    at FilterGrok.<anonymous> (/home/ubuntu/node-logstash/lib/lib/base_component.js:77:10)
```

**Comment by bpaquet** [comment]
Sorry, the doc is wrong.
